### ISSUE TITLE
Update emu default db

### ISSUE THREAD

**Issue by cdvogela** [treangenlab/emu#15]
I would like to update the default emu database (NCBI + rrnDB); in your paper you explain to use the build custom db on both separately and then concatenate, but am not sure how to concatenate both files; in the available version, it seems like duplicate entries are merged, while in the paper it is stated that duplicates are removed?
I see on your OSF page that there is a python script available for generating the silva database; would you have a similar script for the default database? Or could you provide guidance in any other way?

**Comment by kdc10** [comment]
Hi @cdvogela,

Thanks for working towards an updated database! A few questions to answer: 

_how to concatenate both files:_ an Emu database was created from rrn sequences and separately for ncbi using **the same taxonomy** (NCBI taxonomy). The two generated fasta files were then concatenated into one for the default database. Although now, with the current provided scripts, it may be cleaner to concatenate the two sequence fastas between building the database (see below). 

_it seems like duplicate entries are merged, while in the paper it is stated that duplicates are removed:_ here, duplicate entry means identical sequences with identical taxonomy. Merging is thus the same outcome as removing duplicates.

I don't have a script on hand, but here are the steps I would recommend:
1. Download NCBI taxonomy for the names.dmp file and the nodes.dmp file.
2. Download rrn fasta and NCBI 16S fasta. Concatenate into one fasta file. You can use the bash command `cat ncbi.fasta rrn.fasta > merged.fasta`
3. Create a seq2taxid map file. This will be your most timely/complicated step. You need to assign a NCBI taxid (as described in the names/nodes.dmp files) for each sequence id. IIRC, NCBI provides this information for the NCBI database. I believe rrn provides this as well, however, you will likely need to update some of the taxids as the NCBI taxonomy has likely changed since the construction of the rrn database. 
4. Run the emu build-database function with the concatenated fasta, your curated seq2taxid map (contains mapping for both ncbi and rrn sequences), names.dmp, nodes.dmp.

Hope this helps!

**Comment by cdvogela** [comment]
Thank you so much for the clear and detailed explanations! I will try, and get back to you in case I have more questions.

Have a nice day!

**Comment by cdvogela** [comment]
Just some feedback in case anyone in the future is looking to do the same: I applied the solution roughly as described. 

For the seq2taxid.map file, I first created them separately, merged them, and then used the tool taxonkit to check for removed/invalid/merged taxids. I replaced the merged taxids by the current ID, there were no removed/invalid IDs.
