### ISSUE TITLE
How are novel species annotated?

### ISSUE THREAD

**Issue by ashleyp1** [treangenlab/emu#21]
Thanks for making this great tool! I have a clarifying question I haven't been able to find an answer to. How does EMU handle novel species? 

For example, I'm working with soil microbiomes that have been inoculated with a microbial consortium. I know I have a novel Chryseobacterium species that is pretty firmly in the genus Chryseobacterium but is otherwise quite different from all known species of that genus. Using a tool like sintax, my read assignments for this strain only go down to the genus level because its not confident on the species. However, EMU appears to always go down to the species level for read assignments. Does EMU have any way to determine the confidence for each level of phylogeny? Can it say a read belongs to genus Chryseobacterium species unknown or will it always assign a species?

Thanks!

**Comment by kdc10** [comment]
It depends on the minimap2 alignment. If the alignment is good enough that minimap2 makes the alignment, a classification will be forced (if using the default emu database, this will be at the species level since all database reads are at the species level). If no alignment is strong enough for minimap2 to make a call, then the sequence is left unclassified. We demonstrate this in the publication (https://www.nature.com/articles/s41592-022-01520-4) where a novel _Romboutsia_ species shows to be classified as an alternative _Romboutsia_ species that is in the database. If your study prefers a different specificity/sensitivity tradeoff, you can alter the minimap2 parameters.

**Comment by kdc10** [comment]
Minimal peak score (-s) may be the most straightforward or perhaps running alignment score drop (-z). Alternatively, you could use your minimap output sam file, apply a filter for a minimum chaining score (s1; I suspect samtools should be able to handle this), then run emu on your filtered sam file. With any option, it will take a bit of thought and effort to establish a desired threshold though.

**Comment by alexweisberg** [comment]
I have a similar comment, I was wondering if it would be possible for Emu to use Minimap alignment similarity thresholds for showing the confidence in an assignment? For example, the NaMeco pipeline only assigns to a Genus level if the read is <97% similar to the database sequence and does not make a species classification, or only to Order or Family at lower thresholds. Would something like this be possible?

**Comment by kdcurry** [comment]
Yes, I agree this could make sense in our algorithm as well. We will add it to the list of future developments :)
