### ISSUE TITLE
Nanopore 16S read preprocessing 

### ISSUE THREAD

**Issue by Kav57** [treangenlab/emu#29]
Hello, 

Thank you for this tool, its incredibly useful! I have a quick question about whether it is necessary to perform any quality control steps after basecalling before using the EMU tool. 

Currently, I have been using super accurate basecalled reads from MinKNOW straight into EMU but I was wondering if you recommend any QC steps prior to using EMU that filter based on read length or polish the reads before classifying them. I was curious whether this is necessary or if this is something the tool does not need as it will be aligning the reads prior to classification. 

All the best 

James

**Comment by kdc10** [comment]
Hi,

It's difficult to quantify this. In our simulated experiments, we found results to be better without any QC steps we explored. However, these simulated reads do not take into account the complications that arise with real sequences. Emu inherently does a bit of classification correction with its algorithm, but of course, the more accurate the reads and database are, the better. So, if you have a particular liking to certain QC steps/software, go for it (especially chimera detection, since Emu doesn't do anything for this). If your reads seem adequate without it (reasonable lengths/q scores), then I do not think further QC is needed.

**Comment by Kav57** [comment]
Hi, 

Thank you so much for your fast reply. I'm going to have a look at the quality of my reads and see if it looks like they would benefit from filtering before running through EMU. Is it interesting for you to know if I see a difference in the taxonomy recovered with and without QC filtering? I have sequenced the zymobiomics mock community and I'm happy to share the results of how well we recover the taxonomy if this is of interest. 

Thanks again, all the best

**Comment by kdc10** [comment]
Yes, if you generate results to share, I'm sure they would be appreciated by the community. Thank you!
